### ISSUE TITLE
Enable pushing to GitHub Pages in deploy

### ISSUE THREAD

**Issue by qurben** [saltudelft/software-analytics-book#26]
I think that it would be nice to be able to easily view the current version of the book. Such as the following: [software-analytics-book](https://chart-increasing-keyboard-analytics.github.io/software-analytics-book/) (on our fork). This also provides easy access to the [pdf](https://chart-increasing-keyboard-analytics.github.io/software-analytics-book/software-analytics-survey.pdf)/[epub](https://chart-increasing-keyboard-analytics.github.io/software-analytics-book/software-analytics-survey.epub) without having to go through the LaTeX hassle.

To enable this you'd need to set the `GITHUB_PAT` environment variable in Travis CI to a [Private Access Token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) from GitHub. (Make sure to keep it secret so it can't be used from pull-requests and misused in general.)

And in the repo the GitHub pages source needs to be enabled.
![](https://i.imgur.com/m6caFWp.png)

The site would show up at https://saltudelft.github.io/software-analytics-book/

**Comment by Inventitech** [comment]
Did that, to see whether it works we will have to wait for Travis ...

**Comment by Inventitech** [comment]
Works, super nice!
