### ISSUE TITLE
Numeric (ACM) citation style

### ISSUE THREAD

**Issue by mpsijm** [saltudelft/software-analytics-book#33]
@gousiosg wrote in the Brightspace announcement: "I've updated the book front mater to use the ACM format." However, this has not actually happened, and I tried to do it myself, but failed miserably.

When changing the `biblio-style` from `index.Rmd` from `apalike` to `acm`, the build script fails with the error message "! Package natbib Error: Bibliography not compatible with author-year citations."

When changing the `biblio-style` to `plain`, the PDF has numeric citations, but the HTML still has author-year citations.

**Comment by mpsijm** [comment]
@Inventitech Do you happen to know how to fix this? :slightly_smiling_face:

**Comment by qurben** [comment]
The pdf and site require two different configurations, because the markdown is pandoc-ed to `.tex` and to `.html`.

I dabbled around in trying to fix this for the gitbook, that worked. See https://github.com/chart-increasing-keyboard-Analytics/software-analytics-book/tree/acm-citations-gitbook

**Comment by qurben** [comment]
Other resources:
 - https://ulriklyngs.com/blog/acm-articles-with-r-markdown
 - https://github.com/jakobib/pandoc-acm-templates

**Comment by mpsijm** [comment]
While this indeed fixes it for the html rendering, the PDF is still rendered apa-like (with author-year citations)

**Comment by qurben** [comment]
Yes, I didn't touch the  pdf in that branch

**Comment by Inventitech** [comment]
> @Inventitech Do you happen to know how to fix this? slightly_smiling_face

I'm unfamiliar with what @gousiosg had in mind; so adding him here such that he can take a look himself.
