### ISSUE TITLE
How to create an appendix?

### ISSUE THREAD

**Issue by qurben** [saltudelft/software-analytics-book#35]
From the announcement:
> \- Content: You need keep all content in one place (no online tables etc). Move all tables to an appendix per chapter.

As per https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#special-headers It is pretty easy, but appendices should be at the end. So you can't create a chapter appendix in this way.

How should this look?

**Comment by gousiosg** [comment]
I would create a section Appendix after the chapter references (if that is possible). I am not sure whether you can have content after the chapter references though; if it is not possible, make the appendix the last part of each chapter. After we are done with the course, we will move all appendices to the appropriate place, i.e. after the end of the document.

**Comment by qurben** [comment]
I added a non-numbered section to the end of our file using:

```
# Appendix: Build Analytics {-}
```
This works pretty well, you get a new chapter but don't mess up the chapter number for chapters after you. 

It does not seem to be possible to prevent a references list from being generated on this page when there are references in the table.

See also https://chart-increasing-keyboard-analytics.github.io/software-analytics-book/appendix-build-analytics.html#tab:build-analytics-selected-papers

**Comment by gousiosg** [comment]
Looks a bit ugly though...

**Comment by qurben** [comment]
As far as I know you can have a references list on all pages or only at the end by toggling the split_bib option in the gitbook options (https://bookdown.org/yihui/bookdown/html.html#gitbook-style).
